services:
  - type: web
    name: expense-tracker-backend
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_SQL_INIT_MODE
        value: always
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-on-render.onrender.com
    autoDeploy: true
    healthCheckPath: /
